version: "1"

services:
  frontend:
    image: ${AWS_ECR_REPO_FRONTEND}:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_APP_API_URL: ${FRONTEND_URL}


  backend:
    image: ${AWS_ECR_REPO_BACKEND}:latest
    container_name: backend
    ports:
      - "8800:8800"
    environment:
      RDS_HOST: ${RDS_HOST}
      RDS_USER: ${RDS_USER}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_NAME: ${RDS_NAME}
      RDS_PORT: ${RDS_PORT}