version: "1"

services:
  backend:
    container_name: backend
    image: backend-app:latest
    ports:
      - "8800:8800"
    env_file:
      - /home/ec2-user/.env

  frontend:
    container_name: frontend
    image: frontend-app:latest
    env_file:
      - /home/ec2-user/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend